events {}

http {
    upstream backend {
        server backend1:3000 max_fails=2 fail_timeout=30s;
        server backend2:3000 max_fails=2 fail_timeout=30s;
        server backend3:3000 backup;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }
    }
}